package com.iss_mr.getting_started;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Staff implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Staff() {
    }




}